name: fash_vuitton_frontend
description: "Virtual Try-On Flutter App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.6.0
  image_picker: ^1.2.4
  lottie: ^3.1.2
  shared_preferences: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/loadingscreen.json
